### ISSUE TITLE
GeoLocation now requires HTTPS SSL

### ISSUE THREAD

**Issue by bradleyflood** [TheRevivalFellowship/Global-Website#10]
The latest Chrome browser is now requiring HTTPS if we wish to use the Geolocation API -- which we are currently using.
So, looks like we will need https on the website.

**Comment by danielmee** [comment]
I've set that up now. I'll send you an email with the deets.

**Comment by echo1991** [comment]
but my website can't get my location info from geolocation after if use Self signed SSL certificate. I can get locaiton info from geolocation when my website use http,but cant get info after i use https though Self signed SSL certificate.
Do you konw the reason and can you help me ?

**Comment by bradleyflood** [comment]
Sorry @echo1991 not sure of the reason nor can I help you. Very time poor. Try on stackoverflow.com

**Comment by bradleyflood** [comment]
Ok I'll check this out and make sure it's working.
We will also need to ensure users are redirected from `http` to `https` - we can do this via `.htaccess` -- I'll set that up.

**Comment by echo1991** [comment]
@bradleyflood   thank you for your reply. I solved the problem. I use a API called BaiduMap(A API like google map), but the API can't work in websites that use https. Geolocation is not the reason.
