### ISSUE TITLE
make `dev` default branch in github

### ISSUE THREAD

**Issue by bradleyflood** [TheRevivalFellowship/Global-Website#13]
I propose that in the Github settings for this repo that `dev` be the default branch.

Here's how I see the branching structure working:

#### Git branching workflow
`master` -> `dev` -> `feature-xyz` -> `dev` -> `master`

 - **`master`** = Live on `production` and any `staging` servers.
 - **`dev`** = Live `dev` servers, merged back into `master`, default branch.
 - **`feature-xyz`** `local` branch off of `dev`, per feature, pull requested into `dev`, then deleted.

#### Branch Naming convention
 - Developer's Initials - Feature and/or Purpose - Date created.
 - `BF-FixFellowshipFinderGeoLogic-22Apr16`

**Comment by bradleyflood** [comment]
The advantage of having `dev` default is that it becomes the default branch opened when viewing the repo on Github, and it is the default branch selected when creating a pull-request.

**Comment by danielmee** [comment]
Done ;)
