### ISSUE TITLE
Setup HTTPS and SSL cert (+ redirection)

### ISSUE THREAD

**Issue by bradleyflood** [TheRevivalFellowship/Global-Website#15]
Set up LetsEncrypt on server and domain etc.

**Comment by danielmee** [comment]
Sorry @bradleyflood, just noticed this issue which makes my #18 a duplicate. I guess I would suggest that it be included within this release though - the cert. is all set up (I believe) and it's just a matter of adding the [htaccess redirect](https://help.dreamhost.com/hc/en-us/articles/215747758-How-do-I-force-my-site-to-load-securely-with-an-htaccess-file-).
I'll deal with the duplicate issue.

**Comment by bradleyflood** [comment]
Done
https://github.com/TheRevivalFellowship/Global-Website/commit/08be99cee48efea3b7c40a437efa98cba02f9ef5
