### ISSUE TITLE
Automatically closing regions

### ISSUE THREAD

**Issue by bradleyflood** [TheRevivalFellowship/Global-Website#4]
In `list all` view, when expanding a region should any other regions automatically close?

Ie can a use have multiple regions open, such as Australia and Asia? Or will opening Asia cause Australia to 'de-expand'?

Having the ability to have multiple regions open would allow a user to compare details or something. But on the other hand the list could get long and ugly, so auto-closing for them keeps the page small and manageable for them.

Thoughts?

**Comment by danielmee** [comment]
When a different region is clicked the open region will close. So, if they are looking at assemblies in Australia and then click Asia, Australia will collapse.
