### ISSUE TITLE
Hero image layout

### ISSUE THREAD

**Issue by danielmee** [TheRevivalFellowship/Global-Website#6]
There's a subtle difference between the desktop and mobile versions of the hero image - mainly that "many locations" is on one line in the desktop version. Just putting a note here to work out how best to fix this.

**Comment by bradleyflood** [comment]
I've fixed this. For now I'm using two seperate SVG's and just swapping them out with CSS Media Queries. It's not perfect but the SVG's are so light in file size it's not a big deal right now.

**Comment by bradleyflood** [comment]
Note you won't see the fix until I push the latest changes from `dev` branch on to the dev site.
