### ISSUE TITLE
Adjustments on contact forms etc.

### ISSUE THREAD

**Issue by bradleyflood** [TheRevivalFellowship/Global-Website#8]
Inserting email here from Daniel so I can work on it later:

Yeah, was working on this tonight. The quick answer is to just link it again to the typeform so everything goes through the one form.

I started with Typeform when they started and over time they keep knocking features over to the ‘pro’ side which requires an upgrade - another one being hidden fields. I was hoping to pass an identifier to the form so I know where the contact has come from but now that would cost $35pm (so overpriced i feel).

I’m reluctant to change as their system works and looks really good but I think it’s going to be hard to manage all these submissions where I am not sure what the person is asking about. I can just imagine getting a submission that says “the phone number has changed now” and then having to do a back/forth email convo with them determining what the context is.

So the alternative is the Machform system I’ve been using for a while now for the bigger things (camp registrations etc). Here are the details below but if it works badly just leave it.

The basic implementation is to just link to the form:
http://forms.trflife.com/admin/view.php?id=12094

And then add an identifier for wherever the link is being placed:
?id=12094&element_5=global
?id=12094&element_5=newsevent

For fellowship changes, is it possible to have the identifier pick up the assembly, i.e. 
?id=12094&element_5=edit-thevogue

They give an embed code but I think it means having to do our own modal window… I’m also not sure how responsive the form is:

```
<script type="text/javascript">
var __machform_url = 'http://forms.trflife.com/admin/embed.php?id=12094&element_5=global';
var __machform_height = 629;
</script>
<div id="mf_placeholder"></div>
<script type="text/javascript" src="http://forms.trflife.com/admin/js/jquery.min.js"></script>
<script type="text/javascript" src="http://forms.trflife.com/admin/js/jquery.ba-postmessage.min.js"></script>
<script type="text/javascript" src="http://forms.trflife.com/admin/js/machform_loader.js"></script>
```

Anyway, I’ll leave it to you based on how much time it would require.

**Comment by danielmee** [comment]
The basic implementation was added in the latest commit. When the locations/contacts module is ready in the next step we'll look at if a modal window is necessary.
